<html doctype>
	<head jquery title="Dr. Vadim Zaytsev — Pipeline" />
	<body style="background-color:#77A5EE;" onload="off(0);off(1);off(2);">
		<header/>
		<h1>
			Unified Assessment Pipeline for Learning-by-Doing
			<a href="../logos/pipeline.1024.png"><img src="../logos/pipeline.200.png" alt="Unified Assessment Pipeline" title="Unified Assessment Pipeline logo designed by Vadim Zaytsev and generated by Fusion Brain"/></a>
		</h1>
		<hr/>
		<p>
			<a href="https://www.utwente.nl/en/service-portal/organisation-regulations-and-codes-of-conduct/vision-on-learning-and-teaching">Learning-by-doing</a> is a paradigm we follow at the <a href="../ut">University of Twente</a>, among other things, to teach programming to students of various programmes. By doing so, we see programming as a skill of expressing oneself in a rather formal way while embracing the problem and eliciting a solution, learning from both successes and failures along the way. Yet, it requires a constant stream of normative feedback to be successful. Technical Computer Science has long passed the point when this can be provided by professors to each student directly, and heavily rely on teaching assistants. This is an expensive and unreliable method: TAs need to be trained explicitly for their tasks, and still deliver work of varying quality, as repeatedly indicated in student evaluations. However, there is research <a href="https://doi.org/10.1007/978-3-030-80421-3_33">evidence</a> that feedback provided by automated tools, can reach the same level of quality and usefulness.
		</p>
		<p>
			Student deliverables also need to be summatively assessed, which is done differently across programmes and modules, with two large categories of approaches being: reliance on TAs for grading or using external tools. Relying on student assessors suffers from the same complaints as indicated above, plus from limitations imposed by the <a href="https://www.utwente.nl/en/eemcs/education/rules-guidelines/rg/">Examination Board</a>. External grading assistance tools vary greatly per teacher and are neither integrated in the assessment platform nor linked (even implicitly) to the learning goals. Much research is needed to investigate existing and possible techniques for automatic feedback and grading, taking into account recent developments of AI such as <a href="https://chat.openai.com/chat/">large language models</a>. Some programmes also have learning goals which cannot be tested in a simple way at all due to their inherent <a href="https://doi.org/10.1145/3550356.3556505">ill-definedness</a> (possible multiple incomparable solutions, lack of formal theories, heavy design focus, no natural decomposition, abstract concepts).
		</p>
		<p>
			The project aims to create one integrated pipeline that features a platform for students to perform/submit their work, which then can be automatically assessed in some appropriate form. The testing part can be based on existing systems like <a href="https://weblab.tudelft.nl">WebLab</a> from Delft or <a href="https://anubis.dacs.utwente.nl//teacher/">Anubis</a> from UT, or at least inspired by them. The grading and feedback generating part will depend on the nature of assignments: mathematical computations, symbolic evaluations, static code analysis (cf. <a href="https://doi.org/10.1007/S40593-015-0080-X">Ask-Elle</a> from Utrecht, <a href="http://purl.utwente.nl/essays/97567">Apollo++</a> from UT, numerous other examples), artefact quality metrics, code smells, etc. The unique point is that those assessments can be explicitly linked to learning outcomes of the corresponding units, the goal shared with prior projects like <a href="https://github.com/creativeprogrammingatelier/atelier">Atelier</a>, <a href="https://github.com/creativeprogrammingatelier/apollo">Apollo</a> and <a href="https://github.com/arthurrump/apollopp">Apollo++</a>.
		</p>
		<h2 help="alphabetically by surname">Participants</h2>
		<ul>
			<li><a href="https://www.utwente.nl/en/eemcs/hmi/hmi-people-pages/hmi-profile-pages/angelikamaderprofile/">Angelika Mader</a> (principal investigator)</li>
			<li><a href="https://people.utwente.nl/arend.rensink">Arend Rensink</a> (promotor)</li>
			<li><a href="https://www.arthurrump.com/about/">Arthur Rump</a> (doctoral candidate)</li>
			<li><a href="https://grammarware.github.io">Vadim Zaytsev</a> (principal investigator)</li>
		</ul>
		<h2 help="latest first">Deliverables</h2>
		<ul>
			<li>
				Arthur Rump, Vadim Zaytsev.
				<em><a href="http://grammarware.net/writes/#Illdefined2022">A Refined Model of Ill-definedness in Project-Based Learning</a></em>, a paper at <a href="https://conf.researchr.org/track/models-2022/models-2022-educators-symposium">EduSymp @ MoDELS</a>, 2022. 8 pages.
				<ul style="list-style-type:none;">
					<li>
						<!-- <a href="https://doi.org/10.1109/SCAM55253.2022.00027"><code>doi:10.1109/SCAM55253.2022.00027</code></a> -->
						<a href="http://grammarware.net/bib/DifferencingTool2024.bib">(BibTeX)</a>
					</li>
				</ul>
			</li>
			<li>
				Arthur Rump, Vadim Zaytsev, Angelika Mader.
				<em><a href="http://grammarware.net/writes/#PipelineRequirements2025">Requirements for an Automated Assesment Tool for Learning Programming by Doing</a></em>, an Education Track paper at <a href="https://conf.researchr.org/track/icst-2025/icst-2025-education">ICST</a>, 2025. <!-- 8 pages. -->
				<!--
				<ul style="list-style-type:none;">
					<li>
						<doired>...</doired>
						<bibred>PipelineRequirements2025</bibred>
					</li>
				</ul>
				-->
			</li>
		</ul>
		<h2 help="in the media">About us</h2>
		<ul>
			<li><a href="https://www.utwente.nl/en/eemcs/fmt/news%20and%20vacancies/News/2024/1/1297503/incentive-grants-for-vadim-zaytsev-and-moritz-hahn">Incentive grants for Vadim Zaytsev and Moritz Hahn</a></li>
			<li><a href="https://www.utwente.nl/en/service-portal/news-events/news/2023/12/1290130/eemcs-faculty-celebrates-innovation-and-education-initiatives">EEMCS Faculty celebrates innovation and education initiatives</a></li>
		</ul>
		<footer/>
	</body>
</html>
