program:
        function+
function:
        name name+ "=" expr newline+
[binary] expr:
        atom (ops atom)*
[apply] expr:
        name atom+
[ifThenElse] expr:
        "if" expr "then" expr "else" expr
[literal] atom:
        int
[argument] atom:
        name
atom:
        "(" expr ")"
[equal] ops:
        "=="
[plus] ops:
        "+"
[minus] ops:
        "-"
