Program:
        Function+
Function:
        Name Name+ "=" Expr Newline+
[binary] Expr:
        Expr Ops Expr
[apply] Expr:
        Name Expr+
[ifThenElse] Expr:
        "if" Expr "then" Expr "else" Expr
Expr:
        "(" Expr ")"
[argument] Expr:
        Name
[literal] Expr:
        Int
[minus] Ops:
        "-"
[plus] Ops:
        "+"
[equal] Ops:
        "=="
