grammar:
        root::nonterminal* production*
production:
        label::label? nonterminal::nonterminal expression
expression:
        epsilon::EPSILON
        empty::EPSILON
        value::value
        any::EPSILON
        terminal::terminal
        nonterminal::nonterminal
        selectable::(selector::selector expression)
        sequence::(expression+)
        marked::expression
        choice::(expression+)
        optional::expression
        plus::expression
        star::expression
value:
        int::EPSILON
        string::EPSILON
label:
        STR
nonterminal:
        STR
selector:
        STR
terminal:
        STR
