grammar:
        production+
production:
        label? STR defining-metasymbol right-hand-side terminator-metasymbol
label:
        "[" STR "]"
defining-metasymbol:
        ":"
right-hand-side:
        (definition-separator-metasymbol definition)+
terminator-metasymbol:
        "\n"
definition-separator-metasymbol:
        "\n" "        "
definition:
        expression (" " expression)*
expression:
        empty
        epsilon
        any
        value
        selectable-expression
        marked-expression
        repetition-expression
        optional-expression
        terminal
        nonterminal
        group-expression
empty:
        "EMPTY"
epsilon:
        "EPSILON"
any:
        "ANY"
value:
        "INT"
        "STR"
selectable-expression:
        selector::STR "::" expression
marked-expression:
        "<" expression ">"
repetition-expression:
        expression repetition-metasymbol
repetition-metasymbol:
        "+"
        "*"
optional-expression:
        expression optionality-metasymbol
optionality-metasymbol:
        "?"
terminal:
        start-terminal-metasymbol STR end-terminal-metasymbol
start-terminal-metasymbol:
        """
end-terminal-metasymbol:
        """
nonterminal:
        start-nonterminal-metasymbol STR end-nonterminal-metasymbol
start-nonterminal-metasymbol:
        EPSILON
end-nonterminal-metasymbol:
        EPSILON
group-expression:
        start-group-metasymbol expression end-group-metasymbol
start-group-metasymbol:
        "("
end-group-metasymbol:
        ")"
