Grammar:
        C-declarations Yacc-declarations "%%" Grammar-rules "%%" Extra-C-code
Yacc-declarations:
        Yacc-declaration*
Yacc-declaration:
        ("%token" | "%left" | "%right" | "%nonassoc") (Terminal | Literal)+ String?
        "%start" Terminal
Grammar-rules:
        Rule*
Rule:
        NonTerminal ":" (Expression? ("|" Expression?)*)? ";"
Expression:
        Terminal
        NonTerminal
        Literal
        "%prec" Terminal
        C-code
        Expression Expression
