#!/bin/sh

../slps/shared/tools/bgf2bnf   $1/$2.bgf $1/$2.bnf
../slps/shared/tools/bgf2dms   $1/$2.bgf $1/$2.dms
../slps/shared/tools/bgf2sdf   $1/$2.bgf $1/$2.sdf
../slps/shared/tools/bgf2rsc   $1/$2.bgf $1/$2.rsc
../slps/topics/investigation/analysis/overview_bgf.py $1/$2.bgf >tmp.xml || exit -1
xsltproc --stringparam date `date +"%d/%m/%Y"` --stringparam zoo ../../../../grammarware.github.com/_dev/$1.xml --stringparam id $3 --stringparam report ../../../../grammarware.github.com/tmp.xml ../slps/topics/export/hypertext/bgf2fancy.xslt $1/$2.bgf >$1/$2.html || exit -1
if [ -r ../slps/topics/grammars/$3 ]; then
	ls -1 ../slps/topics/grammars/$3/*.xbgf | xargs -n1 -I _ basename _ .xbgf | xargs -n1 -I _ ../slps/shared/tools/xbgf2html ../slps/topics/grammars/$3/_.xbgf $1/$2-_.html `basename $2`.html
fi
